require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PropertyTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PropertyType. As you add validations to PropertyType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "entity_type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PropertyTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all property_types as @property_types" do
      property_type = PropertyType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:property_types).should eq([property_type])
    end
  end

  describe "GET show" do
    it "assigns the requested property_type as @property_type" do
      property_type = PropertyType.create! valid_attributes
      get :show, {:id => property_type.to_param}, valid_session
      assigns(:property_type).should eq(property_type)
    end
  end

  describe "GET new" do
    it "assigns a new property_type as @property_type" do
      get :new, {}, valid_session
      assigns(:property_type).should be_a_new(PropertyType)
    end
  end

  describe "GET edit" do
    it "assigns the requested property_type as @property_type" do
      property_type = PropertyType.create! valid_attributes
      get :edit, {:id => property_type.to_param}, valid_session
      assigns(:property_type).should eq(property_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PropertyType" do
        expect {
          post :create, {:property_type => valid_attributes}, valid_session
        }.to change(PropertyType, :count).by(1)
      end

      it "assigns a newly created property_type as @property_type" do
        post :create, {:property_type => valid_attributes}, valid_session
        assigns(:property_type).should be_a(PropertyType)
        assigns(:property_type).should be_persisted
      end

      it "redirects to the created property_type" do
        post :create, {:property_type => valid_attributes}, valid_session
        response.should redirect_to(PropertyType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved property_type as @property_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyType.any_instance.stub(:save).and_return(false)
        post :create, {:property_type => { "entity_type" => "invalid value" }}, valid_session
        assigns(:property_type).should be_a_new(PropertyType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyType.any_instance.stub(:save).and_return(false)
        post :create, {:property_type => { "entity_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested property_type" do
        property_type = PropertyType.create! valid_attributes
        # Assuming there are no other property_types in the database, this
        # specifies that the PropertyType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PropertyType.any_instance.should_receive(:update).with({ "entity_type" => "" })
        put :update, {:id => property_type.to_param, :property_type => { "entity_type" => "" }}, valid_session
      end

      it "assigns the requested property_type as @property_type" do
        property_type = PropertyType.create! valid_attributes
        put :update, {:id => property_type.to_param, :property_type => valid_attributes}, valid_session
        assigns(:property_type).should eq(property_type)
      end

      it "redirects to the property_type" do
        property_type = PropertyType.create! valid_attributes
        put :update, {:id => property_type.to_param, :property_type => valid_attributes}, valid_session
        response.should redirect_to(property_type)
      end
    end

    describe "with invalid params" do
      it "assigns the property_type as @property_type" do
        property_type = PropertyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyType.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_type.to_param, :property_type => { "entity_type" => "invalid value" }}, valid_session
        assigns(:property_type).should eq(property_type)
      end

      it "re-renders the 'edit' template" do
        property_type = PropertyType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PropertyType.any_instance.stub(:save).and_return(false)
        put :update, {:id => property_type.to_param, :property_type => { "entity_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested property_type" do
      property_type = PropertyType.create! valid_attributes
      expect {
        delete :destroy, {:id => property_type.to_param}, valid_session
      }.to change(PropertyType, :count).by(-1)
    end

    it "redirects to the property_types list" do
      property_type = PropertyType.create! valid_attributes
      delete :destroy, {:id => property_type.to_param}, valid_session
      response.should redirect_to(property_types_url)
    end
  end

end
