require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RealTimeFullScreensController do

  # This should return the minimal set of attributes required to create a valid
  # RealTimeFullScreen. As you add validations to RealTimeFullScreen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RealTimeFullScreensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all real_time_full_screens as @real_time_full_screens" do
      real_time_full_screen = RealTimeFullScreen.create! valid_attributes
      get :index, {}, valid_session
      assigns(:real_time_full_screens).should eq([real_time_full_screen])
    end
  end

  describe "GET show" do
    it "assigns the requested real_time_full_screen as @real_time_full_screen" do
      real_time_full_screen = RealTimeFullScreen.create! valid_attributes
      get :show, {:id => real_time_full_screen.to_param}, valid_session
      assigns(:real_time_full_screen).should eq(real_time_full_screen)
    end
  end

  describe "GET new" do
    it "assigns a new real_time_full_screen as @real_time_full_screen" do
      get :new, {}, valid_session
      assigns(:real_time_full_screen).should be_a_new(RealTimeFullScreen)
    end
  end

  describe "GET edit" do
    it "assigns the requested real_time_full_screen as @real_time_full_screen" do
      real_time_full_screen = RealTimeFullScreen.create! valid_attributes
      get :edit, {:id => real_time_full_screen.to_param}, valid_session
      assigns(:real_time_full_screen).should eq(real_time_full_screen)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RealTimeFullScreen" do
        expect {
          post :create, {:real_time_full_screen => valid_attributes}, valid_session
        }.to change(RealTimeFullScreen, :count).by(1)
      end

      it "assigns a newly created real_time_full_screen as @real_time_full_screen" do
        post :create, {:real_time_full_screen => valid_attributes}, valid_session
        assigns(:real_time_full_screen).should be_a(RealTimeFullScreen)
        assigns(:real_time_full_screen).should be_persisted
      end

      it "redirects to the created real_time_full_screen" do
        post :create, {:real_time_full_screen => valid_attributes}, valid_session
        response.should redirect_to(RealTimeFullScreen.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved real_time_full_screen as @real_time_full_screen" do
        # Trigger the behavior that occurs when invalid params are submitted
        RealTimeFullScreen.any_instance.stub(:save).and_return(false)
        post :create, {:real_time_full_screen => { "name" => "invalid value" }}, valid_session
        assigns(:real_time_full_screen).should be_a_new(RealTimeFullScreen)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RealTimeFullScreen.any_instance.stub(:save).and_return(false)
        post :create, {:real_time_full_screen => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested real_time_full_screen" do
        real_time_full_screen = RealTimeFullScreen.create! valid_attributes
        # Assuming there are no other real_time_full_screens in the database, this
        # specifies that the RealTimeFullScreen created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RealTimeFullScreen.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => real_time_full_screen.to_param, :real_time_full_screen => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested real_time_full_screen as @real_time_full_screen" do
        real_time_full_screen = RealTimeFullScreen.create! valid_attributes
        put :update, {:id => real_time_full_screen.to_param, :real_time_full_screen => valid_attributes}, valid_session
        assigns(:real_time_full_screen).should eq(real_time_full_screen)
      end

      it "redirects to the real_time_full_screen" do
        real_time_full_screen = RealTimeFullScreen.create! valid_attributes
        put :update, {:id => real_time_full_screen.to_param, :real_time_full_screen => valid_attributes}, valid_session
        response.should redirect_to(real_time_full_screen)
      end
    end

    describe "with invalid params" do
      it "assigns the real_time_full_screen as @real_time_full_screen" do
        real_time_full_screen = RealTimeFullScreen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RealTimeFullScreen.any_instance.stub(:save).and_return(false)
        put :update, {:id => real_time_full_screen.to_param, :real_time_full_screen => { "name" => "invalid value" }}, valid_session
        assigns(:real_time_full_screen).should eq(real_time_full_screen)
      end

      it "re-renders the 'edit' template" do
        real_time_full_screen = RealTimeFullScreen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RealTimeFullScreen.any_instance.stub(:save).and_return(false)
        put :update, {:id => real_time_full_screen.to_param, :real_time_full_screen => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested real_time_full_screen" do
      real_time_full_screen = RealTimeFullScreen.create! valid_attributes
      expect {
        delete :destroy, {:id => real_time_full_screen.to_param}, valid_session
      }.to change(RealTimeFullScreen, :count).by(-1)
    end

    it "redirects to the real_time_full_screens list" do
      real_time_full_screen = RealTimeFullScreen.create! valid_attributes
      delete :destroy, {:id => real_time_full_screen.to_param}, valid_session
      response.should redirect_to(real_time_full_screens_url)
    end
  end

end
